### ISSUE TITLE
Small CSS issue

### ISSUE THREAD

**Issue by RUnroe** [josephreed2600/juh.gay#8]
![Screenshot_20230215-194343.png](https://user-images.githubusercontent.com/46465278/219254949-c1bedf26-a302-4cff-b30b-26da2a30153e.png)

When viewing your site on a mobile screen size, the contents of your code block extends horizontally. I am able to scroll to see all of the contents, but the background color of the code block moves with the text. 

< 3

**Comment by josephreed2600** [comment]
Fixed in 049f1de
